# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

parameters:
  - name: projects
    type: object
    default:
    - lotr-books
    - lotr-movies
    
jobs:
  - job:  
    pool:
      lens-build-agent
    steps:
      - script: npm i
      - task: Bash@3
        inputs:
          filePath: './build.sh'
      - ${{each project in parameters.projects}}:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo "Does $(affected) contain ${{project}}?"
        - task: Bash@3
          condition: contains(variables['affected'], '${{project}}')
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo "Build image for ${{project}}"
        - task: Docker@2
          inputs:
            repository: '${{project}}'
            command: 'build'
            Dockerfile: 'apps/${{project}}/Dockerfile'
            buildContext: '.'
            tags:
              dev-latest