# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

parameters:
  - name: projects
    type: object
    default:
    - lotr-books
    - lotr-movies
    
jobs:
  - job:  
    pool:
      lens-build-agent
    steps:
      - script: npm i
      - task: Bash@3
        name: "nx_affected"
        inputs:
          filePath: './build.sh'
          arguments: '$(base)'
      - ${{each project in parameters.projects}}:
        - task: Bash@3
          condition: contains(variables['affected'], '${{project}}')
          inputs:
            targetType: 'inline'
            script: echo "Build image for ${{project}}"
        - task: Docker@2
          condition: contains(variables['affected'], '${{project}}')
          inputs:
            repository: '${{project}}'
            command: 'build'
            Dockerfile: './Dockerfile'
            buildContext: '.'
            tags: |
              $(image-tag)
              ${{ format('{0}{1}{2}{3}{4}{5}{6}', variables['Build.SourceVersion'][0], variables['Build.SourceVersion'][1], variables['Build.SourceVersion'][2], variables['Build.SourceVersion'][3], variables['Build.SourceVersion'][4], variables['Build.SourceVersion'][5], variables['Build.SourceVersion'][6]) }}
            arguments: '--build-arg project=${{project}}'