# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

parameters:
  - name: projects
    type: object
    default:
    - lotr-books
    - lotr-movies
    
jobs:
  - job:  
    pool:
      lens-build-agent
    steps:
      # - script: npm i
      # - task: Bash@3
      #   inputs:
      #     filePath: './build.sh'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            # echo "$(affected)"
            echo "would be affected"
      - ${{each project in parameters.projects}}:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo "$(affected) contains ${{project}} = ${{contains($(affected), project)}}"
        - task: Bash@3
          condition: contains($(affected), ${{project}})
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo "Build image for ${{project}}"
        - task: Bash@3
          condition: not(contains($(affected), ${{project}}))
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo "NOT build image for ${{project}}"
              
      # - task: Docker@2
      #   inputs:
      #     command: 'build'
      #     Dockerfile: 'apps/lotr-books/Dockerfile'
      #     buildContext: '.'