# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
jobs:
  - job:  
    pool:
      lens-build-agent
    steps:
      - script: npm i
      - task: Bash@3
        inputs:
          filePath: './build.sh'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            echo '$affected'
      # - task: Docker@2
      #   inputs:
      #     command: 'build'
      #     Dockerfile: 'apps/lotr-books/Dockerfile'
      #     buildContext: '.'